name: Build Bitcoin Knots Daemon Flatpak

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Flatpak
      run: |
        sudo apt update
        sudo apt install -y flatpak flatpak-builder

    - name: Add Flathub repository
      run: |
        flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
        flatpak install -y flathub org.freedesktop.Platform//22.08
        flatpak install -y flathub org.freedesktop.Sdk//22.08

    - name: Make build script executable
      run: chmod +x build.sh

    - name: Build Flatpak
      run: ./build.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: bitcoin-knots-daemon-flatpak
        path: bitcoin-knots-daemon.flatpak

    - name: Create Release
      if: github.event_name == 'release'
      uses: softprops/action-gh-release@v1
      with:
        files: bitcoin-knots-daemon.flatpak
